# Generated by Django 5.2.3 on 2025-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apphost", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="存储主机远程登录密码（建议加密后存储）",
                max_length=255,
                null=True,
                verbose_name="主机密码",
            ),
        ),
    ]
