# Generated by Django 5.2.3 on 2025-06-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apphost", "0002_host_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="password",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="主机密码"
            ),
        ),
    ]
